version: '3'
services:
  marklog_backend_container:
    build:
      context: ./marklog-backend
      dockerfile: ./Dockerfile
    ports:
      - "7777:8080"
    networks:
      - marklog-network
  marklog_frontend_container:
    build:
      context: ./marklog-frontend
      dockerfile: ./Dockerfile
    ports:
    - "8000:80"
    networks:
      - marklog-network
    depends_on:
      - marklog_backend_container

networks:
  marklog-network: