version: '3'
services:
  marklog_backend_container:
    build:
      context: ./marklog-backend
      dockerfile: ./Dockerfile
    networks:
      - marklog-network
  marklog_frontend_container:
    build:
      context: ./marklog-frontend
      dockerfile: ./Dockerfile
    ports:
    - 80:80
    - 443:443
    environment:
      - CERTBOT_EMAIL=padomay1352@gmail.com
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
      - ./nginx_secrets:/etc/letsencrypt
    networks:
      - marklog-network
    depends_on:
      - marklog_backend_container

networks:
  marklog-network: