version: '3'
services:
  marklog_backend_container:
    image: padomay1352/marklog_backend
    networks:
      - marklog-network
  marklog_frontend_container:
    image: padomay1352/marklog_frontend
    ports:
    - 80:80
    - 443:443
    - 888:888
    environment:
      - CERTBOT_EMAIL=padomay1352@gmail.com
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - marklog-network
    depends_on:
      - marklog_backend_container

networks:
  marklog-network:
